[mypy]
plugins = sqlalchemy.ext.mypy.plugin
strict = True

[mypy-aioboto3.*]
ignore_missing_imports = True

[mypy-botocore.*]
ignore_missing_imports = True

[mypy-aiobotocore.*]
ignore_missing_imports = True

[mypy-jose.*]
ignore_missing_imports = True

[mypy-slowapi.*]
ignore_missing_imports = True

[mypy-passlib.*]
ignore_missing_imports = True
