from app.schemas.common import ErrorResponse, HealthResponse, ReadinessResponse, SuccessResponse
from app.schemas.post import (
    BulkLikesRequest,
    BulkLikesResponse,
    LikeResponse,
    LikeStatusResponse,
    LikeToggleRequest,
    PasswordVerifyRequest,
    PasswordVerifyResponse,
    PinToggleResponse,
    PostCategoryFilter,
    PostCreate,
    PostCreateResponse,
    PostDeleteRequest,
    PostListResponse,
    PostResponse,
    PostSearchType,
    PostSortField,
    PostUpdate,
    PostUpdateResponse,
    ViewIncrementResponse,
)
from app.schemas.comment import (
    CommentCreate,
    CommentCreateResponse,
    CommentDeleteRequest,
    CommentListResponse,
    CommentResponse,
    CommentUpdate,
    CommentUpdateResponse,
)
from app.schemas.inquiry import (
    InquiryCreate,
    InquiryCreateResponse,
    InquiryListResponse,
    InquiryResponse,
    InquiryStatusUpdate,
    InquiryStatusUpdateResponse,
)
from app.schemas.article import (
    ArticleCreate,
    ArticleCreateResponse,
    ArticleListResponse,
    ArticleLocaleInput,
    ArticleResponse,
    ArticleUpdate,
    ArticleUpdateResponse,
)
from app.schemas.admin import (
    AdminLoginRequest,
    AdminLoginResponse,
    AdminStats,
    AdminStatsResponse,
    DeleteImageRequest,
    ImageUploadResponse,
)
from app.schemas.config import SiteConfigResponse, VerificationConfig

__all__ = [
    # common
    "SuccessResponse",
    "ErrorResponse",
    "HealthResponse",
    "ReadinessResponse",
    # post
    "PostSortField",
    "PostSearchType",
    "PostCategoryFilter",
    "PostCreate",
    "PostCreateResponse",
    "PostUpdate",
    "PostUpdateResponse",
    "PostResponse",
    "PostListResponse",
    "PostDeleteRequest",
    "PasswordVerifyRequest",
    "PasswordVerifyResponse",
    "LikeToggleRequest",
    "LikeResponse",
    "LikeStatusResponse",
    "BulkLikesRequest",
    "BulkLikesResponse",
    "ViewIncrementResponse",
    "PinToggleResponse",
    # comment
    "CommentCreate",
    "CommentCreateResponse",
    "CommentUpdate",
    "CommentUpdateResponse",
    "CommentResponse",
    "CommentListResponse",
    "CommentDeleteRequest",
    # inquiry
    "InquiryCreate",
    "InquiryCreateResponse",
    "InquiryResponse",
    "InquiryListResponse",
    "InquiryStatusUpdate",
    "InquiryStatusUpdateResponse",
    # article
    "ArticleLocaleInput",
    "ArticleCreate",
    "ArticleCreateResponse",
    "ArticleUpdate",
    "ArticleUpdateResponse",
    "ArticleResponse",
    "ArticleListResponse",
    # admin
    "AdminLoginRequest",
    "AdminLoginResponse",
    "AdminStats",
    "AdminStatsResponse",
    "ImageUploadResponse",
    "DeleteImageRequest",
    # config
    "VerificationConfig",
    "SiteConfigResponse",
]
